           
jobs:
  build:

    runs-on: ubuntu-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://dasabate-dev.crm4.dynamics.com'
        user-name: 'daniel@dasabate.onmicrosoft.com'
        password-secret: ${{ secrets.MYPASSWORD }}
        solution-name: DeployFlowsSample
        solution-output-file: 'out/Solution.zip'
        working-directory: 'solutions'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/Solution.zip'
        solution-folder: 'solutions/DeployFlowsSample'
        solution-type: 'Unmanaged'
        overwrite-files: true
    
    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'solutions/DeployFlowsSample'
        solution-target-folder: 'src/solutions/DeployFlowsSample'
        token: ${{ secrets.GITHUB_TOKEN }}