# Export solution from DEV environment
#  Unpack it and prepare, commit and push a git branch with the changes
name: 00_devtorepo
run-name: Export solution '${{ inputs.solution_name }}' from environment ${{ inputs.environment_name }} to Repo  by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
        default: 'dasabate-dev'
      solution_name:
        description: 'Solution Name'
        required: true
        default: 'ContosoCore'
      git_comment:
        description: 'Git Comment'
        required: false
        default: 'Updates from DEV environment'
      solution_version_number:
        description: 'Solution Version'
        required: false
        default: '1.0'
    
permissions:
  contents: write           
jobs:
  export:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Get current timestamp
      run: |
        echo "timestamp=$(date +"%Y%m%d")" >> "$GITHUB_ENV"

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Set solution version
      uses: microsoft/powerplatform-actions/set-online-solution-version@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        name: ${{ inputs.solution_name }}
        version: ${{inputs.solution_version_number}}.${{ env.timestamp }}.${{ github.run_number }}

    - name: Publish customizations
      uses: microsoft/powerplatform-actions/publish-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
  
    - name: Export Solution - Unmanaged
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name:  ${{ inputs.solution_name }}
        solution-output-file: 'Solution.zip'
        overwrite: true  

    - name: Export Solution - Managed
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: ${{ inputs.solution_name }}
        solution-output-file: 'Solution_managed.zip'
        managed: true
        overwrite: true

  push:
    needs: export
    runs-on: ubuntu-latest
    steps:

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@latest
      with:
        solution-file: 'Solution.zip'
        solution-type: 'Both'
        solution-folder: 'solutions/${{ inputs.solution_name }}'
        overwrite-files: true
    
    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@latest
      with:
        solution-folder: 'solutions/${{ inputs.solution_name }}'
        solution-target-folder: 'src/solutions/${{ inputs.solution_name }}'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

    - name: Git Fetch and Commit
      run: |
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "@${{ github.actor }}"
        git checkout main
        git add --all 
        git commit -m "${{ inputs.git_comment }}" 
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
