# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write           
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: Debug01
      run: echo "Url = ${{vars.ENVIRONMENT_URL}} ClientId=${{vars.CLIENT_ID}} TenantId=${{vars.TENANT_ID}}"

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: WhoAmI
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}

    - name: Export Solution - Unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: DeployFlowsSample
        solution-output-file: 'Solution.zip'        

    - name: Export Solution - Managed
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: DeployFlowsSample
        solution-output-file: 'Solution_managed.zip'
        managed: true

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'Solution.zip'
        solution-type: 'Both'
        solution-folder: 'solutions/DeployFlowsSample'
        overwrite-files: true
    
    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'solutions/DeployFlowsSample'
        solution-target-folder: 'src/solutions/DeployFlowsSample'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
