# Basic workflow to connect to the Power Platform and run a simple WhoAmI request
name: helloworld
run-name: WhoAmI to ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
        default: 'dasabate-dev'
  
jobs:
  helloworld_job:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
    
    - name: Get current timestamp
      run: |
        echo "timestamp=$(date +"%Y-%m-%d")" >> "$GITHUB_ENV"

    - name: Echo timestamp
      run: echo Timestamp is' ${{ env.TIMESTAMP }}' or is it '$TIMESTAMP'

    - name: WhoAmI
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
       environment-url: ${{ vars.ENVIRONMENT_URL }}
       app-id: ${{ vars.CLIENT_ID }}
       client-secret: ${{ secrets.CLIENT_SECRET }}
       tenant-id: ${{ vars.TENANT_ID }}