# Basic workflow to connect to the Power Platform and run a simple WhoAmI request
name: helloworld
run-name: WhoAmI to ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
        default: 'dasabate-dev'
  
jobs:
  helloworld_job:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
    
    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%YY-%m-%d')}" >> $GITHUB_STATE

    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: nightly-tag-${{ env.date }}
        RELEASE_NAME: nightly-release-${{ env.date }}

    - name: WhoAmI
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
       environment-url: ${{ vars.ENVIRONMENT_URL }}
       app-id: ${{ vars.CLIENT_ID }}
       client-secret: ${{ secrets.CLIENT_SECRET }}
       tenant-id: ${{ vars.TENANT_ID }}