# Basic workflow to connect to the Power Platform and run a simple WhoAmI request
name: helloworld
on:
  workflow_dispatch:
  
jobs:
  helloworld_job:

    runs-on: ubuntu-latest
    environment: dasabate_poc
    
    env:
      RUNNER_DEBUG: 1

      
    steps:

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: WhoAmI
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
       environment-url: ${{ vars.ENVIRONMENT_URL }}
       app-id: ${{ vars.CLIENT_ID }}
       client-secret: ${{ secrets.CLIENT_SECRET }}
       tenant-id: ${{ vars.TENANT_ID }}