name: helloworld
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write           
jobs:
  build:

    runs-on: ubuntu-latest   # alternate runner OS is: ubuntu-latest

    steps:

    - name: Debug01
      run: echo "Debug01"

    - name: Debug02
      run: echo ${{env.ENVIRONMENT_URL}}

    - name: Debug03
      run: echo "Debug03"
      
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{secrets.CLIENT_SECRET}}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: DeployFlowsSample
        solution-output-file: 'out/Solution.zip'
        working-directory: 'solutions'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/Solution.zip'
        solution-folder: 'solutions/DeployFlowsSample'
        solution-type: 'Unmanaged'
        overwrite-files: true
    
    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'solutions/DeployFlowsSample'
        solution-target-folder: 'src/solutions/DeployFlowsSample'
        token: ${{ secrets.GITHUB_TOKEN }}
