# This workflow will deploy an unmanaged solution to a DEV environment
name: 10_repotoenv_unmanaged
run-name: Deploy unmanaged '${{ inputs.solution_name }}' to ${{ inputs.environment_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
        default: 'dev1'
      solution_name:
        description: 'Solution Name'
        required: true
        default: 'BasicSolution'
  pull_request:
    branches: [ "main" ]
 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Pack Solution - Unmanaged
      uses: microsoft/powerplatform-actions/pack-solution@latest
      with:
        solution-file: solution.zip
        solution-folder: 'solutions/${{ inputs.solution_name }}'
        solution-type: 'Unmanaged'

    - name: Deploy Solution to DEV
      uses: microsoft/powerplatform-actions/import-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        solution-file: solution.zip
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}

  
