# Pack solution and deploy it to UAT

name: 20_repotouat
run-name: Deploy to UAT by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Pack Solution - Managed
      uses: microsoft/powerplatform-actions/pack-solution@latest
      with:
        solution-file: pocpublisher_managed.zip
        solution-folder: solutions/PoCPublisher
        solution-type: 'Managed'

    - name: Deploy Solution to UAT
      uses: microsoft/powerplatform-actions/import-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        solution-file: pocpublisher_managed.zip
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
  

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: dasabate_poc
    
  #   env:
  #     RUNNER_DEBUG: 1

  #   steps:

  #   - name: Install Power Platform Tools
  #     uses: microsoft/powerplatform-actions/actions-install@latest


