# This workflow will deploy a solution to UAT environment
name: 20_repotouat
run-name: Deploy to UAT by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
        default: 'dasabate-poc'
      solution_name:
        description: 'Solution Name'
        required: true
        default: 'BasicSolution'
  pull_request:
    branches: [ "main" ]
 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    
    env:
      RUNNER_DEBUG: 1
      
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Pack Solution - Managed
      uses: microsoft/powerplatform-actions/pack-solution@latest
      with:
        solution-file: solution_managed.zip
        solution-folder: solutions/BasicSolution
        solution-type: 'Managed'

    - name: Deploy Solution to UAT
      uses: microsoft/powerplatform-actions/import-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        solution-file: solution_managed.zip
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}

  