name: 30_release
run-name: Release ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Target Environment'
        required: true
        default: 'dasabate-poc'
      solution_name:
        description: 'Solution Name'
        required: true
        default: 'DeployFlowsSample'

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-file: 'out/Solution.zip'
        solution-folder: 'solutions/${{ inputs.solution_name }}'
        solution-type: 'Both'

    - name: Upload artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: out

    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
    

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts 2
      uses: actions/download-artifact@v4

    - name: Display structure of files
      run: ls -R
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@latest

    - name: Import Solution
      uses: microsoft/powerplatform-actions/import-solution@latest
      with:
        environment-url: ${{ vars.ENVIRONMENT_URL }}
        solution-file: 'drop/Solution_managed.zip'
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        activate-plugins: true
        run-asynchronously: true
      