
# Build plugins workflow
name: 40_buildplugins
run-name: BuildPlugins by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder Name'
        required: true
        default: 'ContosoPlugins'
  
jobs:
  build:

    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
    
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: 'Use NuGet'
      uses: nuget/setup-nuget@v1.1.1
      with:
        nuget-version: '4.3.0'

    - name: 'Install msbuild'
      uses: microsoft/setup-msbuild@v2.0.0
    
    - name: 'Nuget restore'
      run: nuget restore ${{ github.workspace }}\src\plugins\SimplePlugin\SimplePlugin.csproj

    - name: 'Run msbuild'
      shell: cmd
      run: msbuild ${{ github.workspace }}\src\plugins\SimplePlugin\SimplePlugin.csproj -t:Restore;Build -p:Configuration=Release;Platform="Any CPU";RestorePackagesConfig=true -maxCpuCount -verbosity:minimal -fileLogger -detailedSummary:False

     # Show repository content
    - name: 'Show repository content'
      run: ls -R ${{ github.workspace }}\src\plugins\SimplePlugin\
