
# Build plugins workflow
name: 40_buildplugins
run-name: BuildPlugins by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'Folder Name'
        required: true
        default: 'ContosoPlugins'
  
jobs:
  build:

    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
    
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: 'Use NuGet'
      uses: nuget/setup-nuget@v1.1.1
      with:
        nuget-version: '4.3.0'

#    - name: 'Restore NuGet packages' 
#      run: nuget restore solution/*.sln

    - name: 'Install msbuild'
      uses: microsoft/setup-msbuild@v1.3.1
    
     # Show repository content
    - name: 'Show repository content'
      run: ls -R

     # Print working directory
    - name: 'Print working directory'
      run: pwd  

    - name: 'Run msbuild'
      shell: cmd
      run: msbuild D:\a\dasbppgithubhalm\dasbppgithubhalm\src\plugins\ContosoPluginsSolution\*.sln -t:Clean -p:First=value;NewProperty=TestResult;Configuration=Release;Platform="x86";RestorePackagesConfig=true -maxCpuCount -v:minimal -fileLogger

