# Workflow to create a new environment in Power Platform
name: 60_provisionenvironment
run-name: Provision environment ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true

  
jobs:
  job:

    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
    
    steps:

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Execute DIR command
      run: |
        dir

    - name:  PAC AUTH WHO
      run: |
        $POWERPLATFORMTOOLS_PACPATH auth who
        

    - name: Create environment
      if: false
      uses: microsoft/powerplatform-actions/create-environment@v1
      with:
        user-name: ${{ secrets.USER_NAME }}
        password-secret: ${{ secrets.PASSWORD_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        name: ${{ inputs.environment_name }}
        type: 'Sandbox'
        region: 'europe'
        currency: 'EUR'
        language: 'English'
        domain: ${{ inputs.environment_name }}

      
        

      



  