# Workflow to create a new environment in Power Platform
name: 60_provisionenvironment
run-name: Provision environment ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true

  
jobs:
  job:

    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
    
    steps:

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      with:
        add-tools-to-path: true

    - name: Create environment
      uses: microsoft/powerplatform-actions/create-environment@v1
      with:
        user-name: ${{ secrets.USER_NAME }}
        password-secret: ${{ secrets.PASSWORD_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        name: ${{ inputs.environment_name }}
        type: 'Sandbox'
        region: 'europe'
        currency: 'EUR'
        language: 'English'
        domain: ${{ inputs.environment_name }}

    - name: PAC CLI - Authenticate
      run: |
        pac auth create --tenant ${{ vars.TENANT_ID }} --username ${{ secrets.USER_NAME }} --password ${{ secrets.PASSWORD_SECRET }}

    - name: PAC CLI - Create Service Principal
      run: |
        pac admin create-service-principal -env https://${{ inputs.environment_name }}.crm4.dynamics.com
      