# Workflow to add users to an environment in Power Platform
name: 70_adduserstoenvironment
run-name: Add users to environment ${{ inputs.environment_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment Name'
        required: true
  
jobs:
  job:

    runs-on: windows-latest
    
    env:
      RUNNER_DEBUG: 1
    
    steps:

    # Checkout the repository
    - name: checkout
      uses: actions/checkout@v4

    # Install and import the required modules
    - name: Install and import modules
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        #Install-Module Microsoft.PowerShell.Utility -Scope CurrentUser
        #Install-Module Microsoft.PowerApps.Administration.PowerShell -Scope CurrentUser
        #Install-Module -Name AzureAD -Scope CurrentUser
        Import-Module AzureAD
        Import-Module Microsoft.PowerShell.Utility
        #Import-Module Microsoft.PowerApps.Administration.PowerShell        
        

    # Call script 01_AddEntraUsersToEnvironment passing in the environment name as parameter
    - name: Add Entra users to environment
      run: |
        .\scripts\01_AddEntraUsersToEnvironment.ps1 -EnvironmentName ${{ inputs.environment_name }}

